# Generated by Django 5.2.7 on 2025-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('saved_videos', models.JSONField(blank=True, default=list)),
                ('category_likes', models.JSONField(blank=True, default=dict)),
                ('saved_channels', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
